### ISSUE TITLE
Maximus Compatibility

### ISSUE THREAD

**Issue by dffischer** [Thoma5/gnome-shell-extension-bottompanel#3] opened 2015-12-05 14:23 UTC
[MaximusTwo](https://github.com/wilfm/GnomeExtensionMaximusTwo), [Pixel Saver](https://github.com/deadalnix/pixel-saver) or any fork of the original Maximus extension remove the title bar of maxmized windows. When used in combination with bottompanel, this makes windows sometimes end up partially off-screen.

![That is a transmission window shyly hiding up there.](https://cloud.githubusercontent.com/assets/6497034/11608199/a1fd3140-9b62-11e5-8f4d-7b0199efc5cb.jpg)

Steps to reproduce:
- have the current versions of [bottompanel](https://extensions.gnome.org/extension/949/bottompanel/) and [Pixel Saver](https://extensions.gnome.org/extension/723/pixel-saver/) both installed and active.
- Possibly restart gnome-shell to make sure to start from a clean state.
- Open any window that does not have a Gtk3 action bar, but a normal title bar. Firefox, Thunderbird or gnome-terminal will do. I used Transmission for the screenshot above.
- Maximize it.
- Place the mouse on an empty space of the panel.
- Press the mouse button and keep it down.
- Drag up.
  The window flickers between the top of the screen and an even higher position until the mouse button is released.

I suspect resolving #2 would fix this, too.

**Comment by tuxor1337** [comment] 2015-12-05 16:01
This is definitely a duplicate of #2. I would close both issues (#2 and this one) because this can only be influenced by an upstream (mutter or gnome-shell) patch.

**Comment by Thoma5** [comment] 2015-12-05 18:08
Closed, because no way to fix it with this extension.

**Closed as completed by Thoma5** 2015-12-05 18:08 UTC

**Comment by dffischer** [comment] 2016-11-18 15:44
For everyone stumbling upon this bug, I just want to leave a note here that the problem seems to be fixed upstream. Testing with GNOME 3.22, all windows I encountered so far stay on screen. Despite #2 still remaining, bottompanel is now at least usable together with Maximus variants.
